wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1646449824
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      4: 3.7.10
      5: 0.12.11
      6: 4.15.0
      8:
      - 5
